### ISSUE TITLE
Whats the latest recommended version?

### ISSUE THREAD

**Issue by zharvey-welltok** [Hazz223/docker-secrets#1]
Hi there! Nifty little project, I could use something like this in lots of my dockerized apps!

This is actually my first Jitpack library (thanks for using it in your build, I've never even heard of it before), so this might be more of a Jitpack-newbie question, but in your README you advise pulling in:

    compile 'com.github.Hazz223:docker-secrets:X.X.X'

I tried using `1.0.0` and get errors in my Gradle project:

```
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find com.github.Hazz223:docker-secrets:1.0.0.
  Searched in the following locations:
      https://jitpack.io/com/github/Hazz223/docker-secrets/1.0.0/docker-secrets-1.0.0.pom
      https://jitpack.io/com/github/Hazz223/docker-secrets/1.0.0/docker-secrets-1.0.0.jar
      https://jcenter.bintray.com/com/github/Hazz223/docker-secrets/1.0.0/docker-secrets-1.0.0.pom
      https://jcenter.bintray.com/com/github/Hazz223/docker-secrets/1.0.0/docker-secrets-1.0.0.jar
  Required by:
      :jitpack-test:unspecified
```

I assume 1.0.0 isn't "available" via Jitpack somehow. Do you know what version of your app I should be using? Even better, how could I look this up myself (e.g. does Jitpack provide available version numbers anywhere, etc.)?

Thanks for any-and-all-steering here! Cheers

**Comment by zharvey-welltok** [comment]
Ahh I finally figured it out, `0.0.1`. Just a function of me being new to Jitpack and fumbling my way around. Closed and thanks again for saving me the trouble of having to do this work myself!

**Comment by Hazz223** [comment]
Mo worries. Glad you got it to work. 
If you've for any other feedback, I'd love to hear it!
